name: Hello Windows 世界！

on: [push]

jobs:
  greet:
    runs-on: windows-latest
    steps:
      - name: ご挨拶
        run: echo "hello！"

      - name: 時間表示
        run: Get-Date

      - name: システムインフォメーション表示
        shell: powershell
        run: systeminfo | findstr /B /C:"OS Name" /C:"OS Version" /C:"System Type"
