name: ZHT Python Docker Action's Test
on: workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - uses: rikkachan20020516-wq/ZHT-custom-actions/ZHT-python-greet@v6
        with:
          name: "Mr.ðŸŒ²"
      - run: echo "Blessingï¼š${{ steps.zht-python-greet.outputs.blessing }}"
