name: "ZHT Python Docker Action's Test"
on: workflow_dispatch

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - id: zht_python_greet
        uses: rikkachan20020516-wq/ZHT-custom-actions/ZHT-python-greet@v6.1
        with:
          name: "Mr.ðŸŒ²"

      - run: echo "Blessing: ${{ steps.zht_python_greet.outputs.blessing }}"
