name: test ZHT's custom Action
on: workflow_dispatch
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: rikkachan20020516-wq/ZHT-custom-actions@main
        with:
          name: "ZHT"
